### ISSUE TITLE
Challenge not checked in verifyAttestation/AssertionResponse

### ISSUE THREAD

**Issue by P4sca1** [MasterKale/WebAuthntine#3]
Hey there!
I noticed that a challenge is passed to generateAttestation/AssertionOptions but when verifying the respone, the returned challenge is never verified.
See step 4: https://www.w3.org/TR/webauthn/#registering-a-new-credential
The verify functions would need another argument where the challenge needs to be passed again.

**Comment by MasterKale** [comment]
Oh my, you're absolutely right...how did I get this far without checking something so fundamental? 😱 

Thanks for catching that, I'll work on a fix right now.

**Comment by MasterKale** [comment]
This has been fixed with PR #5.
