### ISSUE TITLE
@webauthn/browser not working with SSR

### ISSUE THREAD

**Issue by P4sca1** [MasterKale/WebAuthntine#6]
`@webauthn/browser` needs access to `window` when loading the module.
This causes errors in SSR environments, because window is not defined there.
Would be great if loading the module would also work in SSR environment.

**Comment by P4sca1** [comment]
I think this is due to using UMD modules. I don't know if there is a way to make UMD modules work without window.
For `nuxt.js` I came around thir problem my using lazy imports for my webauthn components and only render (and import) those components on the client using `<client-only>`

**Comment by MasterKale** [comment]
Ah, I hadn't considered testing out SSR - it must be because `supportsWebauthn()` checks if `window.PublicKeyCredential` is defined. I can probably add a check before that to see if `window` is defined first...

Can I bother you for some repro instructions, for setting up something on my end I can use to test for SSR support? You can keep it high level, I'm no stranger to JS stuff 😇

**Comment by P4sca1** [comment]
I thought it was the supportsWebauthn() method too at first, but that's not the case. It's true that this method also fails on SSR, because a check for `window` is missing, but the problem occurs earlier when just importing `@webauthn/browser`.

This is because `@webauthntine/dist/webauthntine-browser.min.js` is an UMD module, which requires `window` on load:

```js
!(function (e, t) {
  "object" == typeof exports && "object" == typeof module
    ? (module.exports = t())
    : "function" == typeof define && define.amd
    ? define([], t)
    : "object" == typeof exports
    ? (exports.WebAuthntineBrowser = t())
    : (e.WebAuthntineBrowser = t());
// The following line is the problem.
})(window, function () {
  return (function (e) {
    // ...
  ]);
});
```

**Comment by P4sca1** [comment]
`npx create-nuxt-app webauthn-ssr`
Confirm defaults.
`npm install -S @webauthntine/browser`

Now edit `pages/index.vue` and insert the following after the script tag:
`import { startAssertion } from '@webauthntine/browser'`.
Now run `npm run dev` and visit http://localhost:3000
